### ISSUE TITLE
Panic in src/libxfuse/attr_shortform.rs:46:58 on an Err value: Os

### ISSUE THREAD

**Issue by kklimov-axcient** [KhaledEmaraDev/xfuse#15]
Hello. I'm getting error while trying to mount centos image on FreeBSD 13.1:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', src/libxfuse/attr_shortform.rs:46:58
stack backtrace:
   0:          0x10c97b4 - <unknown>
   1:          0x10a140f - <unknown>
   2:          0x10c945f - <unknown>
   3:          0x10b6e0d - <unknown>
   4:          0x10b742b - <unknown>
   5:          0x10c9b32 - <unknown>
   6:          0x10c9a96 - <unknown>
   7:          0x10b6ec1 - <unknown>
   8:          0x109fb52 - <unknown>
   9:          0x109d352 - <unknown>
  10:          0x104f24e - <unknown>
  11:          0x105ac52 - <unknown>
Abort trap (core dumped)
```
I can suppose that xfs-fuse doesn't work properly with extended attributes like `security.selinux` https://www.crc.id.au/2010/09/29/selinux-on-xfs-filesystems/ but I'm not sure. We are using memory disks to work with offsets. I tried to reproduce this bug:
Created a test image on my Ubuntu machine:
```
~$ dd if=/dev/zero of=xfs_orig.img bs=4k count=5000
~$ mkfs.xfs xfs_orig.img
~$ blkid -o value -s TYPE xfs_orig.img
xfs
```
Then I tried to mount it using xfs-fuse and it was successful:
```
# mdconfig -f xfs_orig.img 
md0
# gnop create -o 0 md0
# xfs-fuse /dev/md0.nop /tmp/ttt/
getattr: 1
access: 1
opendir: 1
access: 1
readdir: 1
access: 1
lookup: "check.txt"
readdir: 1
access: 1
access: 1
releasedir: 1
```
remove memory disk:
```
# mdconfig -d -u md0
```
Then I added extended attribute. To do this I mounted image on my Ubuntu machine and used xattr:
```
sudo xattr -w security.custom custom /tmp/test
sudo xattr -w security.custom custom /tmp/test/check.txt
xattr -l /tmp/test/check.txt
security.custom: custom
sudo umount /tmp/test
```
Then I tried to mount this image using xfs-fuse and got this error:
```
# mdconfig -f xfs_attr.img 
md0
# gnop create -o 0 md0
# xfs-fuse /dev/md0.nop /tmp/ttt/
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', src/libxfuse/attr_shortform.rs:46:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abort trap (core dumped)
```
After that I tried to mount the both images  (memory disks) using lklfuse and it was successful:
```
# lklfuse -o type=xfs,ro,opts="nouuid\,norecovery" -f /dev/md0.nop /tmp/ttt/
[    0.000000] Linux version 4.16.0 (root@132amd64-default-job-13) (gcc version 12.2.0 (FreeBSD Ports Collection)) #1 Fri Aug 4 07:51:01 UTC 2023
[    0.000000] bootmem address range: 0x802a01000 - 0x806a00000
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 16159
[    0.000000] Kernel command line: mem=64M virtio_mmio.device=292@0x1000000:1
[    0.000000] Dentry cache hash table entries: 8192 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] Memory available: 64440k/65532k RAM
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 4096
[    0.000000] lkl: irqs initialized
[    0.000000] clocksource: lkl: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000002] lkl: time and timers initialized (irq2)
[    0.000019] pid_max: default: 4096 minimum: 301
[    0.000085] Mount-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.000096] Mountpoint-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.010786] console [lkl_console0] enabled
[    0.010840] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.010921] xor: automatically using best checksumming function   8regs     
[    0.011101] random: get_random_u32 called from bucket_table_alloc+0x89/0x260 with crng_init=0
[    0.011200] NET: Registered protocol family 16
[    0.334663] raid6: int64x1  gen()  6449 MB/s
[    0.674794] raid6: int64x1  xor()  4793 MB/s
[    1.014782] raid6: int64x2  gen()  7369 MB/s
[    1.354753] raid6: int64x2  xor()  5375 MB/s
[    1.694740] raid6: int64x4  gen() 12424 MB/s
[    2.033454] raid6: int64x4  xor()  4981 MB/s
[    2.374764] raid6: int64x8  gen() 17915 MB/s
[    2.554732] random: fast init done
[    2.714733] raid6: int64x8  xor()  4963 MB/s
[    2.714744] raid6: using algorithm int64x8 gen() 17915 MB/s
[    2.714745] raid6: .... xor() 4963 MB/s, rmw enabled
[    2.714747] raid6: using intx1 recovery algorithm
[    2.714936] clocksource: Switched to clocksource lkl
[    2.715085] NET: Registered protocol family 2
[    2.715251] tcp_listen_portaddr_hash hash table entries: 256 (order: 0, 4096 bytes)
[    2.715264] TCP established hash table entries: 512 (order: 0, 4096 bytes)
[    2.715268] TCP bind hash table entries: 512 (order: 0, 4096 bytes)
[    2.715272] TCP: Hash tables configured (established 512 bind 512)
[    2.715363] UDP hash table entries: 128 (order: 0, 4096 bytes)
[    2.715374] UDP-Lite hash table entries: 128 (order: 0, 4096 bytes)
[    2.715466] virtio-mmio: Registering device virtio-mmio.0 at 0x1000000-0x1000123, IRQ 1.
[    2.715802] workingset: timestamp_bits=62 max_order=14 bucket_order=0
[    2.716806] SGI XFS with ACLs, security attributes, no debug enabled
[    2.720533] io scheduler noop registered
[    2.720542] io scheduler deadline registered
[    2.720600] io scheduler cfq registered (default)
[    2.720624] io scheduler mq-deadline registered
[    2.720625] io scheduler kyber registered
[    2.720638] virtio-mmio virtio-mmio.0: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work.
[    2.723888] virtio_blk virtio0: [vda] 40000 512-byte logical blocks (20.5 MB/19.5 MiB)
[    2.724682] NET: Registered protocol family 10
[    2.725072] Segment Routing with IPv6
[    2.725099] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    2.725497] Btrfs loaded, crc32c=crc32c-generic
[    2.725570] Warning: unable to open an initial console.
[    2.725592] This architecture does not have kernel memory protection.
[    2.727444] XFS (vda): Mounting V5 filesystem in no-recovery mode. Filesystem will be inconsistent.
```
Checked directory:
```
# ls -l /tmp/ttt/ 
total 8
-rw-r--r--  1 root  wheel  13 Aug  8 02:28 check.txt
```
Could you guys help me with this issue.

**Comment by asomers** [comment]
I've found the problem.  @kklimov-axcient told me that the problem only happens when the image is stored in a md device, not a raw file.  Then ktrace revealed what the actual problem was:
```
 55369 xfs-fuse CALL  lseek(0x3,0x1d8,SEEK_CUR)
 55369 xfs-fuse RET   lseek 5669336/0x5681d8
 55369 xfs-fuse CALL  read(0x3,0x185a5d846000,0x2000)
 55369 xfs-fuse RET   read -1 errno 22 Invalid argument
```
It's an unaligned read.  md devices, like all disk devices, can only service reads and writes at sector size boundaries.  By default, those are 512B for md.  But here xfuse seeks to 0x5681d8, which isn't 512B aligned.   The offending code is at https://github.com/KhaledEmaraDev/xfuse/blob/b7b5a4159a2d81164643a8480e2c8473d3dcfd9c/src/libxfuse/dinode.rs#L188 .

But the best solution isn't obvious.  There are 120 other places where xfuse's code seeks, and some of those clearly aren't 512B aligned either.  Since the reader is buffered, some of those seeks won't translate into actual OS-level seeks.  But some will, and it's hard to tell which.  I'll have to study some more to come up with a solution that won't require too much refactoring.  In the meantime, a workaround is to only mount raw files.
