### ISSUE TITLE
Panic when reading a remote extended attribute: "failed to fill whole buffer"

### ISSUE THREAD

**Issue by asomers** [KhaledEmaraDev/xfuse#86]
An XFS extended attribute can either be "local", meaning its value is stored alongside its name, or "remote", meaning its value is stored in a separate block somewhere.  Previously we only had tests for local extended attributes.  I've now discovered that xfuse will panic when it attempts to read a remote attribute.

```
thread 'main' panicked at src/libxfuse/attr.rs:390:42:
called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ace7ea1f7cbba7b4f031e66c54ca237a0d65de6/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/8ace7ea1f7cbba7b4f031e66c54ca237a0d65de6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/8ace7ea1f7cbba7b4f031e66c54ca237a0d65de6/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/8ace7ea1f7cbba7b4f031e66c54ca237a0d65de6/library/core/src/result.rs:1073:23
   4: xfs_fuse::libxfuse::attr::AttrRmtHdr::from
             at ./src/libxfuse/attr.rs:390:9
   5: xfs_fuse::libxfuse::attr::AttrLeafblock::get
             at ./src/libxfuse/attr.rs:298:41
   6: <xfs_fuse::libxfuse::attr_bptree::AttrBtree as xfs_fuse::libxfuse::attr::Attr<R>>::get
             at ./src/libxfuse/attr_bptree.rs:173:12
   7: <xfs_fuse::libxfuse::volume::Volume as fuser::Filesystem>::getxattr
             at ./src/libxfuse/volume.rs:330:35
   8: fuser::request::Request::dispatch_req
             at /home/somers/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fuser-0.13.0/src/request.rs:410:17
   9: fuser::request::Request::dispatch
             at /home/somers/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fuser-0.13.0/src/request.rs:57:25
  10: fuser::session::Session<FS>::run
             at /home/somers/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fuser-0.13.0/src/session.rs:133:34
  11: fuser::mount2::{{closure}}
             at /home/somers/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fuser-0.13.0/src/lib.rs:992:78
  12: core::result::Result<T,E>::and_then
             at /rustc/8ace7ea1f7cbba7b4f031e66c54ca237a0d65de6/library/core/src/result.rs:1316:22
  13: fuser::mount2
             at /home/somers/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fuser-0.13.0/src/lib.rs:992:5
  14: xfs_fuse::main
             at ./src/main.rs:86:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/8ace7ea1f7cbba7b4f031e66c54ca237a0d65de6/library/core/src/ops/function.rs:250:5
```

**Comment by asomers** [comment]
Fixed by #87
